MOCK_PROJECTS = [
    {
        "id": "ayuda-mock-001",
        "name": "Senior Citizen Cash Assistance",
        "requirements": ["Valid ID", "Senior Citizen ID", "Barangay Certificate"],
        "eligibility": ["Age 60 and above", "Resident for at least 6 months"],
        "location": {
            "address": "Municipal Hall, Poblacion",
            "placeId": "ChIJn9XTfA2blzMRyrQ4sYf6NAA",
            "lat": 14.5995,
            "lng": 120.9842,
            "mapsUrl": "https://maps.google.com/?q=14.5995,120.9842",
        },
        "schedule": "2026-06-15T08:30",
        "scheduleEnd": "2026-06-15T11:30",
        "beneficiaryTarget": 180,
        "dependencies": [
            {"id": "dep-mock-001-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-001-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-001-c", "label": "Staff Ready", "ready": True},
        ],
        "publishState": "published",
        "status": "upcoming",
        "statusNote": "Priority lanes will be available.",
        "createdAt": "2026-04-20T09:00:00.000Z",
        "updatedAt": "2026-04-20T09:00:00.000Z",
    },
    {
        "id": "ayuda-mock-002",
        "name": "PWD Food Pack Distribution",
        "requirements": ["PWD ID", "Valid Government ID"],
        "eligibility": ["Registered PWD beneficiary", "Resident of the barangay"],
        "location": {
            "address": "Barangay Gymnasium, San Isidro",
            "placeId": "ChIJ4X7M4fublzMRH6Z80w8FfA0",
            "lat": 14.6123,
            "lng": 120.9765,
            "mapsUrl": "https://maps.google.com/?q=14.6123,120.9765",
        },
        "schedule": "2026-06-10T09:00",
        "scheduleEnd": "2026-06-10T12:00",
        "beneficiaryTarget": 120,
        "dependencies": [
            {"id": "dep-mock-002-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-002-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-002-c", "label": "Staff Ready", "ready": False},
        ],
        "publishState": "published",
        "status": "ongoing",
        "statusNote": "Queue system is active at the entrance.",
        "createdAt": "2026-04-19T10:00:00.000Z",
        "updatedAt": "2026-04-19T10:00:00.000Z",
    },
    {
        "id": "ayuda-mock-003",
        "name": "Emergency Rice Relief",
        "requirements": ["Family Card", "Valid ID"],
        "eligibility": ["Affected by recent flooding"],
        "location": {
            "address": "Covered Court, Riverside",
            "placeId": "ChIJa0J9I7ublzMRSmvYtuYOD00",
            "lat": 14.6201,
            "lng": 121.0014,
            "mapsUrl": "https://maps.google.com/?q=14.6201,121.0014",
        },
        "schedule": "2026-06-12T13:30",
        "scheduleEnd": "2026-06-12T16:30",
        "beneficiaryTarget": 250,
        "dependencies": [
            {"id": "dep-mock-003-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-003-b", "label": "Venue Ready", "ready": False},
            {"id": "dep-mock-003-c", "label": "Staff Ready", "ready": True},
            {"id": "dep-mock-003-d", "label": "Relief Goods Packed", "ready": True},
        ],
        "publishState": "published",
        "status": "moved",
        "statusNote": "Moved from Riverside Chapel to Covered Court due to rain.",
        "createdAt": "2026-04-18T14:30:00.000Z",
        "updatedAt": "2026-04-18T14:30:00.000Z",
    },
    {
        "id": "ayuda-mock-004",
        "name": "Single Parent Transport Assistance",
        "requirements": ["Solo Parent ID", "Valid ID", "School Enrollment Slip"],
        "eligibility": ["Single parent with enrolled student"],
        "location": {
            "address": "City Social Welfare Office",
            "mapsUrl": "",
        },
        "schedule": "2026-06-20T10:00",
        "scheduleEnd": "2026-06-20T13:00",
        "beneficiaryTarget": 90,
        "dependencies": [
            {"id": "dep-mock-004-a", "label": "Funds Ready", "ready": False},
            {"id": "dep-mock-004-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-004-c", "label": "Staff Ready", "ready": False},
        ],
        "publishState": "published",
        "status": "cancelled",
        "statusNote": "Cancelled due to budget reallocation; wait for reschedule notice.",
        "createdAt": "2026-04-17T11:00:00.000Z",
        "updatedAt": "2026-04-17T11:00:00.000Z",
    },
    {
        "id": "ayuda-mock-005",
        "name": "Draft Medical Aid Intake",
        "requirements": ["Medical Abstract", "Hospital Bill"],
        "eligibility": ["Low-income household"],
        "location": {
            "address": "District Office 2",
            "mapsUrl": "",
        },
        "schedule": "",
        "scheduleEnd": "",
        "beneficiaryTarget": 0,
        "dependencies": [
            {"id": "dep-mock-005-a", "label": "Funds Ready", "ready": False},
            {"id": "dep-mock-005-b", "label": "Venue Ready", "ready": False},
            {"id": "dep-mock-005-c", "label": "Staff Ready", "ready": False},
        ],
        "publishState": "draft",
        "status": "upcoming",
        "statusNote": "Draft awaiting schedule confirmation.",
        "createdAt": "2026-04-16T08:15:00.000Z",
        "updatedAt": "2026-04-16T08:15:00.000Z",
    },
    {
        "id": "ayuda-mock-006",
        "name": "Draft Livelihood Starter Kit",
        "requirements": ["Business Plan", "Valid ID", "Barangay Clearance"],
        "eligibility": ["Unemployed resident", "Completed skills orientation"],
        "location": {
            "address": "TESDA Partner Center",
            "placeId": "ChIJj2-5J7ublzMRBvlTYQG1MzA",
            "lat": 14.575,
            "lng": 120.99,
            "mapsUrl": "https://maps.google.com/?q=14.575,120.99",
        },
        "schedule": "2026-07-01T14:00",
        "scheduleEnd": "2026-07-01T17:00",
        "beneficiaryTarget": 45,
        "dependencies": [
            {"id": "dep-mock-006-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-006-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-006-c", "label": "Staff Ready", "ready": False},
            {"id": "dep-mock-006-d", "label": "Starter Kits Procured", "ready": False},
        ],
        "publishState": "draft",
        "status": "upcoming",
        "statusNote": "Draft pending procurement checks.",
        "createdAt": "2026-04-16T12:10:00.000Z",
        "updatedAt": "2026-04-16T12:10:00.000Z",
    },
    {
        "id": "ayuda-mock-007",
        "name": "Fisherfolk Fuel Subsidy",
        "requirements": ["Fisherfolk Registry ID", "Boat Registration"],
        "eligibility": ["Registered fisherfolk", "Active within municipal waters"],
        "location": {
            "address": "Port Authority Satellite Office",
            "placeId": "ChIJOxwV9mWblzMRg6mXaZtKxO4",
            "lat": 14.545,
            "lng": 120.97,
            "mapsUrl": "https://maps.google.com/?q=14.545,120.97",
        },
        "schedule": "2026-06-28T07:00",
        "scheduleEnd": "2026-06-28T10:00",
        "beneficiaryTarget": 70,
        "dependencies": [
            {"id": "dep-mock-007-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-007-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-007-c", "label": "Staff Ready", "ready": True},
            {"id": "dep-mock-007-d", "label": "Fuel Vouchers Printed", "ready": True},
        ],
        "publishState": "published",
        "status": "upcoming",
        "statusNote": "Bring your own container for token redemption.",
        "createdAt": "2026-04-15T06:30:00.000Z",
        "updatedAt": "2026-04-15T06:30:00.000Z",
    },
    {
        "id": "ayuda-mock-008",
        "name": "Daily Wage Worker Meal Support",
        "requirements": ["Employment Certificate", "Valid ID"],
        "eligibility": ["Daily wage earner", "No active subsidy in current month"],
        "location": {
            "address": "Community Center, North Zone",
            "mapsUrl": "",
        },
        "schedule": "2026-06-11T11:30",
        "scheduleEnd": "2026-06-11T14:30",
        "beneficiaryTarget": 150,
        "dependencies": [
            {"id": "dep-mock-008-a", "label": "Funds Ready", "ready": True},
            {"id": "dep-mock-008-b", "label": "Venue Ready", "ready": True},
            {"id": "dep-mock-008-c", "label": "Staff Ready", "ready": True},
        ],
        "publishState": "published",
        "status": "ongoing",
        "statusNote": "Meal packs are released by batch number.",
        "createdAt": "2026-04-15T09:45:00.000Z",
        "updatedAt": "2026-04-15T09:45:00.000Z",
    },
]
